services:
  cdt-monitor:
    image: skytianyu/cdt-monitor:latest
    container_name: cdt-monitor
    restart: always
    network_mode: host
    volumes:
      - ./data:/var/www/html/data
    environment:
      - TZ=Asia/Shanghai  
      - WEB_PORT=43210
